version: "2.4"

services:
  rocketchat-preview:
    image: stanick/rocket.chat
    container_name: rocket.chat
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - /RocketChatTransfert:/app/bundle/programs/web.browser/app/tmp
